// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ownowyxauejpteqlwvcw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93bm93eXhhdWVqcHRlcWx3dmN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNDM1MTQsImV4cCI6MjA3MTcxOTUxNH0.iowLjoVoan2a6_OrdVbzAKtMDUUsreBa05DZyJlTxmc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});